version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./DockerfileDev
    restart: on-failure
    expose:
      - "8000"
#    ports:
#      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ./DockerfileDev
    env_file:
      - ./frontend/.env
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/logs:/var/log/nginx/
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached
